### ISSUE TITLE
libjpeg-turbo8 dependency incorrect on Raspbian

### ISSUE THREAD

**Issue by fnoop** [CanberraUAV/cuav#5]
The documented libjpeg-turbo8 dependency is not available on Raspbian (Raspberry Pi Debian).  It looks like the package might be called libturbojpeg1-dev, on Raspbian, but not sure.

**Comment by stephendade** [comment]
Thanks for catching that. I've edited the documentation to reflect this (http://canberrauav.github.io/cuav/build/html/installing/index.html).
