### ISSUE TITLE
optimizing block_xmit

### ISSUE THREAD

**Issue by Janphr** [CanberraUAV/cuav#58]
Hey,

I'd like to use your block_xmit implementation for a project of mine, but the example 'a simple test suite' seems little slow. I was able to speed it up a little by setting `packet_count` and `max_queue` of the tick method.
Increasing the `bandwidth` and `chunk_size` helped too, but could you provide an example optimized for performance?
If I set bandwidth to 5MB/s a 600MB file should be sent in about 2 Minutes, but it takes much longer. 
With a bandwidth of 100MB/s it takes around 80 Seconds.
```
bandwidth = 100000000
num_blocks = int(total_size/65535)
chunk_size=65535
packet_count=1000
max_queue=50
```

Thanks!

**Comment by tridge** [comment]
it was written for much slower links, and the python implementation will consume a lot of cpu

**Comment by Janphr** [comment]
Thanks for replying. Yes I already managed to do what I wanted using pythons socket modules. 
Sry, I would have deleted the issue if i had the rights. 
Best regards!
